# permissions to do viewer ingressdaemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressdaemonset-viewer-role
rules:
- apiGroups:
  - ingressdaemonsets.mumoshu.github.io
  resources:
  - ingressdaemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingressdaemonsets.mumoshu.github.io
  resources:
  - ingressdaemonsets/status
  verbs:
  - get
