// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotateNodeToDetach) DeepCopyInto(out *AnnotateNodeToDetach) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotateNodeToDetach.
func (in *AnnotateNodeToDetach) DeepCopy() *AnnotateNodeToDetach {
	if in == nil {
		return nil
	}
	out := new(AnnotateNodeToDetach)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckerSpec) DeepCopyInto(out *HealthCheckerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckerSpec.
func (in *HealthCheckerSpec) DeepCopy() *HealthCheckerSpec {
	if in == nil {
		return nil
	}
	out := new(HealthCheckerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressDaemonSet) DeepCopyInto(out *IngressDaemonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressDaemonSet.
func (in *IngressDaemonSet) DeepCopy() *IngressDaemonSet {
	if in == nil {
		return nil
	}
	out := new(IngressDaemonSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngressDaemonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressDaemonSetList) DeepCopyInto(out *IngressDaemonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IngressDaemonSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressDaemonSetList.
func (in *IngressDaemonSetList) DeepCopy() *IngressDaemonSetList {
	if in == nil {
		return nil
	}
	out := new(IngressDaemonSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngressDaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressDaemonSetSpec) DeepCopyInto(out *IngressDaemonSetSpec) {
	*out = *in
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
	if in.HealthCheckNodePorts != nil {
		in, out := &in.HealthCheckNodePorts, &out.HealthCheckNodePorts
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	out.HealthChecker = in.HealthChecker
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressDaemonSetSpec.
func (in *IngressDaemonSetSpec) DeepCopy() *IngressDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(IngressDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressDaemonSetStatus) DeepCopyInto(out *IngressDaemonSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressDaemonSetStatus.
func (in *IngressDaemonSetStatus) DeepCopy() *IngressDaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(IngressDaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateSpec) DeepCopyInto(out *RollingUpdateSpec) {
	*out = *in
	if in.MaxUnavailableNodes != nil {
		in, out := &in.MaxUnavailableNodes, &out.MaxUnavailableNodes
		*out = new(int)
		**out = **in
	}
	if in.MaxDegradedNodes != nil {
		in, out := &in.MaxDegradedNodes, &out.MaxDegradedNodes
		*out = new(int)
		**out = **in
	}
	if in.MaxUnavailablePodsPerNode != nil {
		in, out := &in.MaxUnavailablePodsPerNode, &out.MaxUnavailablePodsPerNode
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxSurgedPodsPerNode != nil {
		in, out := &in.MaxSurgedPodsPerNode, &out.MaxSurgedPodsPerNode
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.AnnotateNodeToDetach != nil {
		in, out := &in.AnnotateNodeToDetach, &out.AnnotateNodeToDetach
		*out = new(AnnotateNodeToDetach)
		(*in).DeepCopyInto(*out)
	}
	if in.WaitForDetachmentByAnnotatedTimestamp != nil {
		in, out := &in.WaitForDetachmentByAnnotatedTimestamp, &out.WaitForDetachmentByAnnotatedTimestamp
		*out = new(WaitForDetachmentByAnnotatedTimestamp)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateSpec.
func (in *RollingUpdateSpec) DeepCopy() *RollingUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStrategySpec) DeepCopyInto(out *UpdateStrategySpec) {
	*out = *in
	in.RollingUpdate.DeepCopyInto(&out.RollingUpdate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStrategySpec.
func (in *UpdateStrategySpec) DeepCopy() *UpdateStrategySpec {
	if in == nil {
		return nil
	}
	out := new(UpdateStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForDetachmentByAnnotatedTimestamp) DeepCopyInto(out *WaitForDetachmentByAnnotatedTimestamp) {
	*out = *in
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForDetachmentByAnnotatedTimestamp.
func (in *WaitForDetachmentByAnnotatedTimestamp) DeepCopy() *WaitForDetachmentByAnnotatedTimestamp {
	if in == nil {
		return nil
	}
	out := new(WaitForDetachmentByAnnotatedTimestamp)
	in.DeepCopyInto(out)
	return out
}
